name: Backend
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: mvn clean install -DskipTests

      - name: Connect to PostgreSQL
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '15.2'
          postgresql db: ics
          postgresql user: postgres
          postgresql password: password
       
      - name: Run Unit Tests
        run: mvn spring-boot:run -Dspring-boot.run.profiles=test

      - name: Run SpotBugs Analysis
        run: mvn spotbugs:check 

