name: Backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
           java-version: '18'
           distribution: 'temurin'
           cache: maven
          
      - name: Bulid JAR
        run: mvn clean install -DskipTests
      - name: Setup DB
        uses: actions/setup-db@v3
        with:
          postgresql db: ics
          postgresql user: postgres
          postgresql password: password
      - name: Run Unit Tests
        run: mvn spring-boot:run -Dspring-boot.run.profiles=test

      - name: Run SpotBugs Analysis
        run: mvn spotbugs:check 
