name: Backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
           java-version: '18'
           distribution: 'temurin'
           cache: maven
          
      - name: Bulid JAR
        run: mvn clean install -DskipTests
        
      - name: Run Unit Tests
        run: java -jar target/demo-0.0.1-SNAPSHOT.jar test

      - name: Run SpotBugs Analysis
        run: mvn spotbugs:check 
